openapi: "3.0.0"
servers:
  - url: http://127.0.0.1:8000
info:
  description: Upload and generate reports
  version: "1.0.0"
  title: Reports API
  contact:
    name: Tommy Nguyen
    email: tommynguyen9330@gmail.com
paths:
  /api/reports/upload:
    post:
      operationId: "views.reports.ReportsView.upload_report"
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: object
      requestBody:
        description: CSV report file
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              required:
                - file
  /api/reports:
    get:
      operationId: "views.reports.ReportsView.generate_payroll_report"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: object
      parameters:
        - name: type
          in: query
          required: true
          schema:
            type: string
            enum:
              - payroll